#!/bin/bash
export QT_SELECT=5
echo -- Downloading git repository...
if [ ! -d "git" ]; then
        mkdir git
fi
cd git
if [ -d "UNO" ]; then
        rm -rf ./UNO
fi
git clone https://github.com/TheShayy/UNO.git
echo -- Launching configure script...
cd UNO
./configure
echo -- Launching make...
cd src
make -j`nproc`
echo -- Killing UNO...
killall .startUNO
killall UNO
echo -- Replacing with the new one...
cp -rf ./{UNO,startUNO,updateUNO,translations/} ../../../
echo -- Launching UNO...
cd ../../..
./startUNO
echo -- Done !
